/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package de.bespire.io.wkt.tests

import com.google.inject.Inject
import de.bespire.io.wkt.wkt.WKT
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(WellKnownTextInjectorProvider)
class WellKnownTextParsingTest {

	@Inject
	ParseHelper<WKT> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello XText!
		''')
		Assert.assertNotNull(result)
	}

}
