/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package de.bespire.io.wkt.validation

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class WellKnownTextValidator extends AbstractWellKnownTextValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGeodeticCrsNameNotEmpty(GeodeticCRS crs) {
//		if (crs.name.length == 0) {
//			warning('Name must not be empty', 
//					WktPackage.Literals.GEODETIC_CRS__NAME,
//					INVALID_NAME)
//		}
//	}
//
//	@Check
//	def checkVerticalCrsNameNotEmpty(VerticalCRS crs) {
//		if (crs.name.length == 0) {
//			warning('Name must not be empty', 
//					WktPackage.Literals.VERTICAL_CRS__NAME,
//					INVALID_NAME)
//		}
//	}
//	
}
